### ISSUE TITLE
Production/dev dependencies mixed

### ISSUE THREAD

**Issue by farridav** [gb-libs/pydantic-geojson#4]
You have your dev dependencies mixed into your production dependencies, which stops me being able to install this via poetry, as I have a later version of pytest than this package requires.

I suggest moving these lines from your pyproject.toml 

```
isort = "^5.10.1"
pytest = "^6.2.5"
``` 

under the heading `[tool.poetry.dev-dependencies]` 

This will also save people shipping pytest and isort along with their production code :)

Thanks

**Comment by farridav** [comment]
Sure thing, here it is https://github.com/gb-libs/pydantic-geojson/pull/5

**Comment by folt** [comment]
Good job @farridav , thank you.
